civicrm/civicrm-sysadmin-guide

docs/planning/transition.md
I think this is worth saying.  Not sure this is the best or right place.  Feedback welcome.
=> Draft Choosing a Consultant/Service Providers

docs/troubleshooting.md
Changed an "it's" to "its." Changed a "you" to "your."
=> Correct minor typos

docs/upgrade/backdrop.md, mkdocs.yml
@seanmadsen added Backdrop page for upgrade steps.
=> Create backdrop.md for upgrade

docs/misc/staging-production.md
Improved the writing, removed inaccurate info, replaced with correct info.
=> Rewrite staging-production docs

docs/planning/transition.md
=> transition.md fix typo

docs/install/multi-site.md
Update to WP multisite section based on chat on WordPress MM channel. It was quite outdated
=> Update WP multisite section

docs/customize/settings.md
Also added updated link to master branch not 4.4
=> made clearer the need for global $civicrm_setting;

docs/setup/civimail/index.md
It depends on your server configuration and may not be the best option.
=> Don't say "Just use mail() if you can"

docs/install/drupal7.md
=> fix broken link

docs/setup/security.md
close issue #38 if the patch is accepted
=> add cross-ref to PHPIDS in dev guide

docs/requirements.md
Minor typo... (the manges) - (and manages)
=> Typing correction

mkdocs.yml
=> Change 'Integration' to 'CMS Integration'

docs/setup/security.md
A response to #36. Close the issue if the PR is accepted.
=> link a commment on SE content on filesystem

docs/integration/wordpress/plugins.md
Expanded section to properly reflect the vast feature set of CiviCRM Admin Utilities.
=> Updated CiviCRM Admin Utilities description.

docs/requirements.md
This makes the note a bit more prominent and puts it in line with the rest of the documentation on Mcrypt extension
ping @MegaphoneJon
=> Make 7.2 mcrypt note more prominent and put it against mcrypt Section

docs/upgrade/index.md
I'm moving this note about evaluating new permissions to the "parent class" of the upgrade docs.  Once this is merged, #134 should be good to merge without changes.
=> Add note about evaluating new permissions

docs/upgrade/drupal7.md
=> simplify upgrade steps

docs/requirements.md
I added the addition of teh SHOW VIEW permissions required for multilingual CiviCRM to work
=> shaneonabike: Added additional MySQL requirements for CiviCRM

docs/setup/payment-processors/index.md
Cleaned up a bit of txt for clarity
=> added country to Authorize.

docs/customize/settings.md
ping @eileenmcnaughton @totten 
Screenshot of the change
=> dev/core#1035 Document HTTP timeout setting

docs/misc/switch-cms.md
This PR fixes a broken link in the switch-cms file introduced by PR #177
=> Fix broken link in misc/switch-cms.md

docs/requirements.md
https://github.com/civicrm/civicrm-core/commit/d7a896b4ae53357064936464a1983dd102905151#commitcomment-34487166
=> Mark PHP 5.6 as incompatible

docs/setup/logging.md
This updates the detailed logging documentation to reflect the changes made in https://github.com/civicrm/civicrm-core/pull/14256.
Additionally, it adds some notes on log table migration and adds a reference to a new extension allowing for more flexible configuration of log tables.
=> dev/core#663 - Update logging section to reflect new engine default

docs/install/joomla.md
The sections aren't numbered and just use a link directly.
=> joomla: clean up note

docs/setup/payment-processors/index.md
Made Edits @MikeyMJCO suggested - I fully expect more Payment Processor Extensions to be shipping w/ Core in future.
=> Update Payment Processor doc

docs/planning/cms.md
This is a PR to deal with #181 and #33.
=> Refactor the planning/cms page as per #181

docs/upgrade/wordpress.md
It's important to not forget the information about the extension folders
=> Modify doc to include ext folder information

docs/setup/optimizations.md
=> Add in documentation on smart group performance tuning

docs/install/wordpress.md
=> Clarify front-end pages clean-url settings.

docs/misc/switching-cms/drupal-to-wordpress.md
This never worked for me until I actually disabled Foreign key checks during the install. I added some information with regards to help others.
=> Updated to include foreign key check disable

docs/requirements.md
=> dev/core#1145 Add in documentation on MySQL 8 Support information

docs/setup/payment-processors/index.md
@eileenmcnaughton @MikeyMJCO I've updated the section on Stripe as suggested by Josh. This could really do with a major cleanup so I've added "Needs Updating" as a note but I think we're more likely to achieve that by incremental improvements.
I also wonder whether we should just remove the whole table.
=> Update section on Stripe and indicate that much of this is out of date.

docs/customize/paths.md, mkdocs.yml
=> Add in details on overriding civicrm paths in civicrm.settings.php

docs/upgrade/wordpress.md
Updated a note about the CiviCRM 4.7 civicrm.settings.php restore
=> Update Upgrading Wordpress Docs

docs/install/multi-site.md
Sorely needed additions, as I spent close to an ENTIRE week fighting with this. Finally figured it out. The Internet should be able to learn from my mistakes (and frustration).
=> Adding WordPress multi-site specific instructions

docs/integration/wordpress/plugins.md
Add Content Views CiviCRM with CiviCRM Data Processor plugin details
Agileware Ref: WPCV-31
=> Add Content Views CiviCRM plugin

docs/integration/wordpress/plugins.md
Add details about the CiviCRM ACF Integration plugin, https://github.com/christianwach/civicrm-acf-integration
=> Add CiviCRM ACF Integration plugin

docs/integration/wordpress/plugins.md
Add WordPress CiviCRM UX plugin
Agileware Ref: WPCIVIUX-86
=> Add WordPress CiviCRM UX plugin

docs/customize/settings.md
Per https://github.com/civicrm/civicrm-core/pull/16636
and https://lab.civicrm.org/dev/core/-/issues/1837
=> Update placeholder for setting

docs/integration/drupal/webform8.md, mkdocs.yml
=> Drupal 8 Webform 

docs/setup/civimail/outbound.md
This updates the documentation to bring the documentation into line with  PR #17709 and should not be executed until after that PR has completed.
=> dev/core#1768 - Update to reflect this change.

docs/setup/payment-processors/recurring.md
Per https://civicrm.org/blog/kcristiano/civicrm-526-and-wordpress-important-notice.
=> update IPN docs for new public-facing URLs on WP

docs/setup/optimizations.md
Documents new efficiency improvement brought in by https://github.com/civicrm/civicrm-core/pull/17745
=> Document new CIVICRM_EXCLUDE_DIRS_PATTERN constant
