civicrm/civicrm-sysadmin-guide

docs/troubleshooting.md

This is a partial cleanup - but I'm guessing it'll be easier to review in chunks, so submitting now.
* "General Advice" is successfully rewritten and much condensed.
* I've removed all "Symptoms" and "Solutions" that simply don't apply to modern (>= 4.6) CiviCRM.
* I removed instructions for the Schema Harmonizer tool, which has more up-to-date instructions on its README.
Still TODO:
* There's still a lot of "Symptoms" and "Solutions" which need re-writing, or extraction into a Stack Exchange question (i.e. they deal with some obscure bug).
* Much of the troubleshooting instructions assume Drupal, we should edit out the Drupalisms.

Toward #14 - Make a useful troubleshooting page

---

docs/setup/jobs.md
docs/setup/site-key.md
mkdocs.yml

I'm trying to do some major improvements on the docs for scheduled jobs, but this content is very tricky to organize! I've put a lot of hours into this already, but I think I need some help from others because I'm unsure about a few things here. Tagging @MegaphoneJon @mlutfy @joannechester @michaelmcandrew @seamuslee001 to see if any of you want to help me answer some of the outstanding questions here.
* This [User Guide PR](https://github.com/civicrm/civicrm-user-guide/pull/228) references sections in the `jobs.md` Sysadmin Guide page in this PR.
This PR is mostly taking content from the following sources and re-organizing it into two pages that clearly target system administrators:
* https://wiki.civicrm.org/confluence/display/CRMDOC//Managing+Scheduled+Jobs
* …

Re-write content on scheduled jobs

---

docs/upgrade/joomla.md

* Update upgrade process to match what is actually required.
* Add known issues as released versions of CiviCRM do not work properly prior to 4.7.29 and this seems the best place to flag this.

Minor adjustments to upgrade process

---

docs/requirements.md

@seanmadsen this adds a note about SQL modes as we have seen some issues with full group by as evidenced by https://civicrm.stackexchange.com/search?q=only_full_group_by. I think this will at least point people potentially towards how to solve issues perhaps

Add node to requirements document about MySQL SQL Modes

---

docs/install/backdrop.md
docs/install/drupal7.md
docs/install/joomla.md
docs/install/wordpress.md
docs/integration/drupal/index.md
docs/planning/demo.md
docs/requirements.md
docs/upgrade/joomla.md
docs/upgrade/wordpress.md

This PR intends to resolve #70 by removing mentions to the forum. 
* Instead of directing users to the forum for generic help, direct them to Mattermost and Stack Exchange.
* Retains links to *specific* forum posts.

Remove generic mentions to forum

---

docs/install/wordpress.md
docs/integration/wordpress/index.md
docs/requirements.md
docs/upgrade/wordpress.md

This PR generalizes the language here so that all references to CiviCRM 4.7 apply equally to CiviCRM 5.0. I think it should be okay to merge now since it dosen't mention 5.0 explicitly. As well, I think that once 5.0 is released, we shouldn't need to make any more changes to the Sysadmin Guide.

Prepare for CiviCRM 5.0 release

---

docs/upgrade/index.md

https://github.com/civicrm/civicrm-core/pull/11864
Note that the actual earliest version that will work on 4.7 & the best interim version could be a bit debated but I think the most important thing is to give an instruction that will work for the (few if any) people dealing with really old versions

Advise need for an interim upgrade version if < 4.2.9

---

docs/requirements.md

I have been running CiviCRM locally with PHP 7.1 for development purposes for many months now. I've been keeping an eye out for errors and notices, and all has seemed well. 
By the end of this year, 7.1 will be the lowest version of PHP that's not EOL'd, so I think we better start officially recommending that people use it. This [question came up on Mattermost](https://chat.civicrm.org/civicrm/pl/u1u7i8n5zjffpruz5da5e7matr).
Then, I think in 2019-01 we should remove "Recommended" from PHP versions below 7.1. I'm really not sure where this leaves the LTS version, but that's a question for another day!

Recommend PHP 7.1 for civi 5.x.x

---

docs/planning/hosting.md

I added a section about CiviCRM Spark, which is the easiest way to get started with CiviCRM.
I also bumped the part on "experts" higher up, because that should also be the logical step in getting started, and we want to promote partners.

hosting.md: added section on Spark, changes to partners

---

docs/setup/jobs.md

Closes https://github.com/civicrm/cv/issues/41.  Also rearranges the arguments - both methods work, but this is the documented correct order.

Cron jobs - Document use of --cwd argument now available in cv

---

docs/setup/civimail/index.md

Overview
----------------------------------------
On some business cases, it may be required to be able to edit an activity type of 'Inbound E-mail', for example, to add an observation or edit some custom fields to implement some kind of workflow. However, this is currently not possible, as the prohibition for this type of activities is hard-coded in several parts within CiviCRM.
This new option to allow users to edit activities of Inbound Email type is being added on this PR:
https://github.com/civicrm/civicrm-core/pull/12445

CRM-21425: Make Inbound Emails Editable With Configuration Option

---

docs/requirements.md

@agh1 per your comments on gitlab proposing this. I also removed 'recommended' from the aging versions but didn't change to 'not recommended' as we are still getting there on that.
I wonder about removing the 4.7 column from this chart?

Update php 7.2 as compatible & recommended

---

docs/integration/drupal/group-roles.md

CiviGroup Roles Sync works with both static and smart groups.

Removed outdated warning against smart groups

---

docs/setup/security.md

Corrects the PCI guidance, which has been wrong since the advent of PCI 3 on 1 Jan 2015.  Also changed this and next section from h3 to h2 because it was a sub-section of an h2 on using SSL, and PCI compliance is no longer just a sub-topic of the decision to use SSL. I have deliberately not gone into Stripe and Braintree, which are (allegedly) compliant under SAQ A when using iframes for the card details form. That is not really a CiviCRM topic, and is anyway controversial.

Update section on PCI compliance

---

docs/requirements.md

closes issue #91 and removes coverage of mysql 5.1, which was EOL in 2013

fixes msising REFERENCES in mysql permissions

---

docs/requirements.md

Oops - pardon the whitespace stripping, my text editor did that automatically!
The *ACTUAL* changes are:
* Changed MySQL minimum version to 5.5 from 5.1;
* MySQL permissions were identical for "5.1.6-5.7.6" and "5.7.6+" now, so I removed the duplicate;
* Moved `CREATE VIEW` into the list of required permissions instead of breaking it out into an, "If you use CiviCase" section.

Remove references to supporting MySQL 5.1; clean up MySQL permissions

---

docs/setup/civimail/inbound.md

note that in the modern schema (5.8) that 30 is actually the new threshold for 'away'.  This assumes I suppose that you might send a couple dozen emails while a person was on extended vacation.  that doesn't necessarily mean they should be on hold.

update on hold threshold and clarify instructions

---

docs/misc/switch-servers.md

As I noted in issue #85, the section on the phpMyAdmin migration mainly repeats the procedures already set out, substituting the use of phpmyadmin for a database export and import into a pre-install CiviCRM db. The steps for the db export in this phpmyadmin section may or may not create errors, and importing a full db dump, including cache tables, into an empty db, is simpler and cleaner. 
The whole phpmyadmin section has been removed, and a brief note on using phpMyAdmin for export/import added in the main sequence of text. This section is still available publicly at https://wiki.civicrm.org/confluence/display/CRMDOC42/Alternate+Moving+the+database+using+phpMyAdmin

Mostly remove the instructions on phpmyadmin

---

docs/setup/payment-processors/authorize-net.md
docs/setup/payment-processors/paypal-pro.md
docs/setup/payment-processors/paypal-standard.md
docs/setup/payment-processors/recurring.md
mkdocs.yml

This keeps on coming up on stackexchange / mattermost.  I've already documented the IPN URLs properly for the stripe extension (https://lab.civicrm.org/extensions/stripe/blob/master/docs/recur.md) so this is basically a copy of that documentation put in a shared location, and all docs for payment processors in this guide pointed to it instead of repeating the same thing, and getting it wrong in different ways!

Sort out documentation for IPN notify URL so it is in a shared location.

---

docs/requirements.md

The information about Drupal 8 isn't totally accurate. I think the most accurate description is something like, "it works, but isn't officially supported." The bug that's linked to also isn't very helpful: that bug is essentially resolved, but requires using some unofficial processes and tools.
So, this PR is an attempt to clarify things!
It links to the README.md in civicrm-drupal-8 under the assumption that this PR, https://github.com/civicrm/civicrm-drupal-8/pull/22, or some variation of it will get merged soon, and then that README can be where the docs about how to get Drupal 8 going can live.

Attempt to clarify the status of Drupal 8 support

---

docs/customize/settings.md

It's possible to 'get stuck' with a site where, once changed, you cannot change the SSL settings back through the GUI.  Without these published conveniently, someone has to dig through the code to find them to fix their site

added useful SSL settings

---

docs/setup/payment-processors/authorize-net.md

also add a warning against using a Silent-post URL that will trigger server redirects.

Add tested cURL script for verifying Silent-post URL

---

docs/setup/jobs.md

One is the standard cron log suppression, the other about the requirement of being run in php cli mode.

jobs: added two notes for cv

---

docs/install/drupal7.md

We say that Drupal 6 is deprecated, so let's not document it in the D7 DB setup docs; it'll only confuse people using D7 here IMO.

Remove D6 DB URL from D7 docs.

---

README.md
content-migration/new-content/requirements.md
docs/index.md
docs/install/backdrop.md
docs/install/joomla.md
docs/install/wordpress.md
docs/misc/switch-cms.md
docs/misc/switch-servers.md
docs/planning/hosting.md
docs/setup/backups.md
docs/setup/cache.md
docs/setup/index.md
docs/setup/jobs.md
docs/setup/logging.md
docs/setup/security.md
docs/setup/site-key.md
docs/upgrade/backdrop.md
docs/upgrade/drupal7.md
docs/upgrade/index.md
docs/upgrade/joomla.md
docs/upgrade/version-specific.md
docs/upgrade/wordpress.md

Some $EDITORs tidy up whitespace on save, which can lead to unrelated tidy-up appearing in commits.
To avoid this "noise", submitting an MR that does this for all current md files.
Done with:
```
perl -pi -e 's#(^.*)[ \t]+$#$1#g' *md */*md */*/*md
```

Remove EOL whitespace in .md files

---

docs/requirements.md

PHP 7.1 is out of date from 1 Dec 2019

Update requirements.md - PHP 7.1

---

docs/misc/switching-cms/drupal-to-wordpress.md

I found that this option is no longer available and I believe autodetected by CiviCRM

Remove reset of table prefixes from Drupal => Wordpress mgiration

---

docs/planning/cms.md

The paragraph after the bullet list of CMSes, was shown in the bullet list. (Together with 'Wordpress')

Missing new line in cms.md

---

docs/requirements.md

Drupal 8 now has an official release!
Drupal 6 isn't really worth mentioning anymore.
WP should be 4.9+ per https://lab.civicrm.org/dev/wordpress/-/issues/51

Update CMS version requirements

---

docs/integration/wordpress/incompatibilities.md

Not sure the best way to handle this, but it's no longer a problem.  I have a feeling that most, if not all, of the Backbone JQuery call issues listed on the page were fixed at the same time.  As stated, I believe this was around the 4.7.29 release.

Added fix info about Salient Theme

---

docs/customize/settings.md

@eileenmcnaughton this is a small revision to clarify the meaning of `domain` - ie it does still signify a distinction between domain-level and contact-level settings.

settings.md - Add more thorough explanation of 'domain'

---

docs/upgrade/index.md

4.2 is super old. I'm bumping up the minimum recommended upgrade version to 4.4, which [was released back in 2013](https://civicrm.org/blog/colemanw/civicrm-44-is-here)!

Bump recommended min upgrade version to 4.4.7

---

docs/upgrade/version-specific.md

Discussion of the impetus for this: https://lab.civicrm.org/dev/wordpress/-/issues/66
Note: The text here refers to changes in 5.29.  The impetus, however, is that the changes were first released in 5.27.  The expectation is that is to revert from 5.27 and then release modified form in 5.29.  However, we should have the docs ready hyperlinking in various comms.

dev/wordpress#66 - Document transition for `wp-content/plugins/files/civicrm`

---

docs/upgrade/version-specific.md

Refrence https://github.com/civicrm/civicrm-core/pull/18068   In testing I left out declaring the global as I copy/pasted from the docs.   Let's add the global in to make it clear that it is needed.

add global to code snippet to make it easier to copy and paste

---

docs/integration/wordpress/incompatibilities.md

Remove YOAST SEO from list of incompatible plugins. The reference is old and YOAST SEO has been working just fine with CiviCRM for over 2 years now.

Remove YOAST SEO from list of incompatible plugins
